# pre-commit stop running hooks after the first failure.
fail_fast: true
# A list of repository mappings
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Remove spaces at end of lines except markdown
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '(\.obsidian|site/stylesheets|site/ja|site/search|site/tags|site/assets|site/ja/development|site/ja/development/embedded|site/ja/development/cloud|site/ja/development/database|site/ja/development/tools|site/ja/development/programming|site/ja/development/embedded/raspberrypi|site/ja/development/embedded/raspberrypi/raspberrypi\-ubuntu|site/ja/development/cloud/aws|site/ja/development/cloud/aws/aws\-cli|site/ja/development/cloud/aws/dynamodb|site/ja/development/cloud/aws/dynamodb/dynamodb\-local|site/ja/development/database/mariadb|site/ja/development/database/mongodb|site/ja/development/database/dynamodb|site/ja/development/database/mongodb/images|site/ja/development/database/mongodb/pymongo|site/ja/development/database/mongodb/mongosh|site/ja/development/database/mongodb/install\-mongodb|site/ja/development/database/mongodb/mongodb\-compass|site/ja/development/tools/shortcuts|site/ja/development/tools/design|site/ja/development/tools/editors|site/ja/development/tools/version\-control|site/ja/development/tools/document|site/ja/development/tools/design/inkscape|site/ja/development/tools/design/inkscape/images|site/ja/development/tools/editors/vscode|site/ja/development/tools/editors/vi|site/ja/development/tools/editors/vscode/images|site/ja/development/tools/editors/vscode/extention|site/ja/development/tools/editors/vscode/settings|site/ja/development/tools/version\-control/git|site/ja/development/tools/version\-control/git/git\-hook|site/ja/development/tools/version\-control/git/git\-hook/pre\-commit|site/ja/development/tools/version\-control/git/git\-hook/post\-commit|site/ja/development/tools/document/markdown|site/ja/development/tools/document/pkm|site/ja/development/tools/document/mkdocs|site/ja/development/tools/document/pkm/obsidian|site/ja/development/tools/document/pkm/workflowy|site/ja/development/tools/document/pkm/obsidian/community_plugins|site/ja/development/tools/document/pkm/obsidian/images|site/ja/development/tools/document/pkm/obsidian/community_plugins/auto_template_trigger|site/ja/development/tools/document/pkm/obsidian/community_plugins/plantuml|site/ja/development/tools/document/mkdocs/doc_config|site/ja/development/tools/document/mkdocs/display\-config|site/ja/development/programming/applescript|site/ja/development/programming/python|site/ja/development/programming/applescript/example|site/ja/development/programming/python/images|site/ja/development/programming/python/pymysql|site/ja/development/programming/python/mdformat|site/ja/development/programming/python/dash\-plotly|site/assets/images|site/assets/img|site/assets/stylesheets|site/assets/javascripts|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min)/.*'
      # Make the last line of the file a newline code
      - id: end-of-file-fixer
        exclude: '(\.obsidian|site/stylesheets|site/ja|site/search|site/tags|site/assets|site/ja/development|site/ja/development/embedded|site/ja/development/cloud|site/ja/development/database|site/ja/development/tools|site/ja/development/programming|site/ja/development/embedded/raspberrypi|site/ja/development/embedded/raspberrypi/raspberrypi\-ubuntu|site/ja/development/cloud/aws|site/ja/development/cloud/aws/aws\-cli|site/ja/development/cloud/aws/dynamodb|site/ja/development/cloud/aws/dynamodb/dynamodb\-local|site/ja/development/database/mariadb|site/ja/development/database/mongodb|site/ja/development/database/dynamodb|site/ja/development/database/mongodb/images|site/ja/development/database/mongodb/pymongo|site/ja/development/database/mongodb/mongosh|site/ja/development/database/mongodb/install\-mongodb|site/ja/development/database/mongodb/mongodb\-compass|site/ja/development/tools/shortcuts|site/ja/development/tools/design|site/ja/development/tools/editors|site/ja/development/tools/version\-control|site/ja/development/tools/document|site/ja/development/tools/design/inkscape|site/ja/development/tools/design/inkscape/images|site/ja/development/tools/editors/vscode|site/ja/development/tools/editors/vi|site/ja/development/tools/editors/vscode/images|site/ja/development/tools/editors/vscode/extention|site/ja/development/tools/editors/vscode/settings|site/ja/development/tools/version\-control/git|site/ja/development/tools/version\-control/git/git\-hook|site/ja/development/tools/version\-control/git/git\-hook/pre\-commit|site/ja/development/tools/version\-control/git/git\-hook/post\-commit|site/ja/development/tools/document/markdown|site/ja/development/tools/document/pkm|site/ja/development/tools/document/mkdocs|site/ja/development/tools/document/pkm/obsidian|site/ja/development/tools/document/pkm/workflowy|site/ja/development/tools/document/pkm/obsidian/community_plugins|site/ja/development/tools/document/pkm/obsidian/images|site/ja/development/tools/document/pkm/obsidian/community_plugins/auto_template_trigger|site/ja/development/tools/document/pkm/obsidian/community_plugins/plantuml|site/ja/development/tools/document/mkdocs/doc_config|site/ja/development/tools/document/mkdocs/display\-config|site/ja/development/programming/applescript|site/ja/development/programming/python|site/ja/development/programming/applescript/example|site/ja/development/programming/python/images|site/ja/development/programming/python/pymysql|site/ja/development/programming/python/mdformat|site/ja/development/programming/python/dash\-plotly|site/assets/images|site/assets/img|site/assets/stylesheets|site/assets/javascripts|site/assets/javascripts/lunr|site/assets/javascripts/workers|site/assets/javascripts/lunr/min)/.*'
        # Unify line break code to LF
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '(\.obsidian/.*)'
      # toml syntax check
      - id: check-toml
      # yaml syntax check
      - id: check-yaml
        # Exclude check for "could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji'"
        args: [--unsafe]

  # https://python-poetry.org/docs/pre-commit-hooks/#usage
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        verbose: true
      - id: poetry-lock
        verbose: true
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt",
          "--without-hashes"]
        verbose: true
        files: ^pyproject\.toml$

  # https://github.com/shellcheck-py/shellcheck-py?tab=readme-ov-file#usage
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.5
    hooks:
      - id: actionlint

  # Reference: https://github.com/DavidAnson/markdownlint-cli2#overview
  # > markdownlint-cli is a traditional command-line interface for markdownlint.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.jsonc", "README.md", "docs/**/*.md"]

  # Reference: https://github.com/DavidAnson/markdownlint-cli2#overview
  # > markdownlint-cli2はmarkdownlint用の少し型破りなコマンドラインインターフェイスです。
  # > markdownlint-cli2は設定ベースで、速度とシンプルさを優先しています。
  # > markdownlint-cli2はmarkdownlint-cliのすべての機能をサポートしています（少し異なる場合もあります）。
  #- repo: https://github.com/DavidAnson/markdownlint-cli2
  #  rev: v0.10.0
  #  hooks:
  #    - id: markdownlint-cli2
  #      args:
  #        [
  #          "--fix",
  #          "--config",
  #          ".markdownlint.jsonc",
  #          "README.md",
  #          "docs/**/*.md",
  #        ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: ["--fix", "ci"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests==2.32.0.20240622]
        args: [--config-file=pyproject.toml]
